theme: jekyll-theme-architect
title: cpansewicz.github.io
# description: A description of my new site.8??

# The baseurl should be an empty string for hosting at the root
baseurl: "" 
# The url should be your live site's URL
url: "https://cpansewicz-github-io.onrender.com/" 
